import Head from "next/head";
import Link from "next/link";
import { ReactNode } from "react";
import Profile from "@/components/Profile";
import { Noto_Sans_JP } from "next/font/google";
import { Turret_Road } from "next/font/google";

const notoJp = Noto_Sans_JP({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-notojp",
});
const turrentRoad = Turret_Road({
  weight: ["500"],
  subsets: ["latin"],
  variable: "--font-turretroad",
});

interface Props {
  children: ReactNode;
}

export default function Layout({ children }: Props) {
  const navLinkList = [
    {
      path: "/",
      name: "HOME",
    },
    {
      path: "/log",
      name: "LOG",
    },
    {
      path: "/about",
      name: "ABOUT",
    },
  ];

  return (
    <>
      <Head>
        <title>Loliver&apos;s Landscape</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={`${notoJp.variable} font-sans h-screen flex flex-col`}>
        <header className="p-2 pb-0 border-b-4 border-indigo-600">
          <div
            className={`container mx-auto text-center text-3xl logo ${turrentRoad.className}`}
          >
            Loliver&apos;s Tech &amp; Life Landscape
          </div>
          <nav>
            <ul className="flex flex-row list-none justify-center text-xl">
              {navLinkList.map((navItem) => (
                <li className="w-44 text-center" key={navItem.path}>
                  <Link href={navItem.path}>{navItem.name}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>

        <main className="flex justify-center grow bg-gradient">
          <div className="flex gap-4 flex-wrap w-[1300px] mx-auto my-4">
            <div className="bg-white flex-auto p-6 xl:max-w-[960px] rounded-md">
              {children}
            </div>
            <div className="xl:w-80 grow">
              <div className="bg-white rounded-md p-6">
                <Profile />
              </div>
            </div>
          </div>
        </main>

        <footer className="bottom-0 p-2 text-center">
          <div>Copyright &copy; 2023 Daichi Furukawa All Rights Reserved.</div>
        </footer>
      </div>
    </>
  );
}
