name: Deploy My Jamstack Blog
on:
  push:
    branches:
      - main
      - develop
      - hotfix/deploy-setting

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Create env file
        shell: bash
        run: |
          touch .env
          echo "SERVICE_DOMAIN=${{ secrets.CMS_SERVICE_DOMAIN }}" >> .env
          echo "API_KEY=${{ secrets.CMS_API_KEY }}" >> .env

      - name: Build
        run: yarn build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
          echo "AWS S3 copy"
          aws s3 cp --recursive --region ap-northeast-1 .out/ s3://${{ secrets.AWS_S3_BUCKET }}
          echo "AWS CloudFront reset"
          aws cloudfront create-invalidation --region ap-northeast-1 --distribution-id ${{ secrets.AWS_CF_ID }} --paths "/*"
